### get the UI page

GET http://localhost:3000/


### create new user

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username":"sano",
    "password":"sanofer"
}

### login user

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username":"sano",
    "password":"sanofer"
}


### fetch all todos

GET http://localhost:3000/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzUzMTc1NTUxLCJleHAiOjE3NTMyNjE5NTF9.dFasc-wrgH8WFJW-BEaWz5ohqTcqOh1skRbA9gsODaU

